# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listreview',
            old_name='list',
            new_name='list_id',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reviews_api.MediaChoice'),
        ),
    ]
